### ISSUE TITLE
Timeline sorting by timeframe is off

### ISSUE THREAD

**Issue by maybeanerd** [maybeanerd/diluz.io#394]
**Describe the bug**
It looks like in Marcs profile e.g. feral jobs are above entries like rove, which should not come after them.

**To Reproduce**
1. Go to marcs profile 
2. Look at feral entries in conparison to the rove entries

**Expected behavior**
A Job that started and ended before 2020 should be listed below a project that started 2020

**Additional context**
It might be related to different entry types? Job vs sideproject
Could also be that the "current" enddate confuses it.

**Comment by maybeanerd** [comment]
Just had a quick look into the code, and I think this is the reason: https://github.com/maybeanerd/diluz.io/blob/main/components%2Fprofile%2Fprojects.vue#L34

Idk why I put it exactly there, it should be kind of a tie breaker, but not more important than the actual dates.

**Comment by mdiluz** [comment]
Hmm, both of them are marked as `ProjectType.job` though?

**Comment by maybeanerd** [comment]
Just to be on the same page here:

![Screenshot_2024-02-03-13-25-24-45.jpg](https://github.com/maybeanerd/diluz.io/assets/18548570/6058c17a-ddcc-430f-9aa1-0fdc818caca9)

Both feral entries are in correct order, but rover is not, right? 
And rover seems to be marked as sideproject, whereas the feral entries are marked as jobs

**Comment by mdiluz** [comment]
Nah, it was the two Feral jobs that are out of order (I became a Lead in 2015). The real conclusion here is PEBCAK, looks like I put the dates in for my Feral jobs the wrong way around.

**Comment by mdiluz** [comment]
Agreed on the side project ordering being a little weird, though tbh I'll probably remove Rove at some point - it was a fun little tech experiment that didn't really go anywhere!

**Comment by maybeanerd** [comment]
Oooh now I get what you meant

Then i'll keep this issue open for the sideproject vs job order, since I so think I want that to behave differently
will hopefully get to adjusting that in the upcoming days or so
